### ISSUE TITLE
Usage with external github action

### ISSUE THREAD

**Issue by brunolemos** [sbellone/release-workflow-example#2]
I'm trying to use Deploy Key with gh-action-bump-version. 

Do you know if secrets.GITHUB_TOKEN is automatically set by the github checkout action when using ssh-key?
I'm still facing the branch protected rule error.

More context: https://github.com/phips28/gh-action-bump-version/issues/260

```yml
steps:
  - uses: actions/checkout@v4
    with:
      ref: refs/heads/dev
      ssh-key: ${{ secrets.DEPLOY_KEY }} # Private ssh key
      persist-credentials: true # <<-- Does this expose a token to GITHUB_TOKEN?
  - id: bump-package-version
    uses: 'phips28/gh-action-bump-version@master'
    with:
      commit-message: 'CI: bumps version to {{version}} [skip ci]'
      default: 'minor'
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Tried with or without this line; how to use the ssh auth?
      PACKAGEJSON_DIR: packages/editor
```

<img width="1114" alt="Image" src="https://github.com/user-attachments/assets/81b9e02d-60a4-4e7d-8fc0-209277593b0e" />
